apiVersion: v2
name: godnsweb
description: A Helm chart for GoDNS Web UI - React-based web interface for GoDNS

# Chart type
type: application

# Chart version
version: 0.1.0

# Application version
appVersion: "0.1.0"

# Icon for the chart
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/coredns/icon/color/coredns-icon-color.svg

# Keywords for easier discovery
keywords:
  - dns
  - web-ui
  - react
  - frontend
  - godns

# Home page
home: https://github.com/rogerwesterbo/godns

# Source code
sources:
  - https://github.com/rogerwesterbo/godns

# Maintainers
maintainers:
  - name: rogerwesterbo
    email: roger.westerbo@example.com
# Dependencies (if any)
# dependencies:
#   - name: ingress-nginx
#     version: "4.x.x"
#     repository: https://kubernetes.github.io/ingress-nginx
#     condition: ingress.enabled
